--- 
:window_x: 100
:window_y: 100
:window_width: 800
:window_height: 800
:current_flip_book_directory: 
:template_directory: ""
:slide_show_interval: 5
:slide_show_loops: false
:navigation_buttons_shown: true
:information_bar_shown: true
:status_bar_shown: true
:thumbnails_shown: true
